### ISSUE TITLE
Natural instance for Store?

### ISSUE THREAD

**Issue by patrickt** [mgsloan/store#154]
Unless there’s some reason why this doesn’t already exist, I imagine this can just piggyback atop the `Integer` instance. If anyone else needs this, I’m happy to send a patch.

**Comment by mgsloan** [comment]
Feel free to send a patch!  I do not have a need for it, but it seems good
to add.  Reusing Integer's encoding makes sense.

**Comment by patrickt** [comment]
Does this look acceptable to you, @mgsloan? If so, I’ll send a patch.

```haskell
instance Store Natural where
  size = contramap fromIntegral (size :: Size Integer)
  poke = poke . toInteger
  peek = fmap fromIntegral (peek :: Peek Integer)
```

**Comment by mgsloan** [comment]
Looks great, thanks Patrick!
