### ISSUE TITLE
Update compatability matirx for ghc 7.8.4

### ISSUE THREAD

**Issue by yaitskov** [mgsloan/store#157]
https://matrix.hackage.haskell.org/#/package/store

cell 0.7.8 is red, but it should be dark green, isn't it?

**Comment by mgsloan** [comment]
Hmm!  Thanks for letting me know.  Based on the error in the matrix builder
there might be a straightforward fix by adding a dependency on the `nats`
package.  I've pushed store-0.7.9 with that fix.

Unfortunately, I could not figure out how to build with ghc-7.8 with modern
stack, and so deleted the build configuration.  So it is currently in a
state of working but truly supported anymore.  If it breaks in a more
complex way I will probably drop support for it.

**Comment by yaitskov** [comment]
Thanks, @mgsloan.
cborg CI is green again.
