### ISSUE TITLE
Support for GHC 9?

### ISSUE THREAD

**Issue by ranjitjhala** [mgsloan/store#160]
Hi @mgsloan, 

Can you give me a sense of any plans to update `store` to work with `ghc 9`?

I recently switched `liquidhaskell` from `binary` to `store`  -- and it was *awesome* -- in the blink of an eye, `store` was deserializing files that took `binary` literally hours (!) 

Unfortunately, it turns out that it breaks our `ghc9` build. So am wondering what your plans are, e.g. whether its doubtful in the short term, or if I should try to send a patch or, if its already in the works?

Thanks so much!

- Ranjit.

**Comment by mgsloan** [comment]
Awesome, I'm glad you've found store to be helpful for liquidhaskell!  I
have not not started work on a patch, but I can try to write one soonish.
I will comment here if I start working on it.  In the meantime, I'd gladly
merge a PR adding support for ghc 9

**Comment by facundominguez** [comment]
I made a try in #161.

**Comment by ranjitjhala** [comment]
Wow, that's awesome thank you @facundominguez !!!

**Comment by ranjitjhala** [comment]
Wow, that's awesome thank you @facundominguez !!!

Shall we update the LH `cabal.ghc9.project` to get your version of `store` until 
it is pulled into the mainline, put on hackage etc?

**Comment by mgsloan** [comment]
Thanks @facundominguez - this is now released on hackage as version `0.7.12` :)

**Comment by ranjitjhala** [comment]
wow, thank you so much @facundominguez and @mgsloan !!!

**Comment by mgsloan** [comment]
Glad it's finding use in Liquid Haskell!  Such a cool project!

https://github.com/mgsloan/store/blob/master/src/System/IO/ByteBuffer.hs
uses Liquid Haskell to verify some memory safety constraints :)
