### ISSUE TITLE
No CI

### ISSUE THREAD

**Issue by sjakobi** [mgsloan/store#166]
A basic CI setup would most likely have caught issues like #162 and #165.

I usually use https://github.com/haskell-CI/haskell-ci, but I don't know how well it works with HPack. If you're interested, I can give it a stab though.

**Comment by mgsloan** [comment]
Sure, go for it!  Yes, unfortunately this repo no longer has CI due to
travis-ci.org ceasing builds.

It'd be fine to check in cabal files.
