### ISSUE TITLE
0.7.17 package on Hackage does not include fix for time 1.11

### ISSUE THREAD

**Issue by Vekhir** [mgsloan/store#177]
Hi @mgsloan,
When building the new version `0.7.17`, I still got the same error as in #176 which got fixed in #175. Looking at the source over at Hackage ([test/Data/StoreSpec.hs](https://hackage.haskell.org/package/store-0.7.17/src/test/Data/StoreSpec.hs)), we can see that the fix is somehow missing:
```
#if MIN_VERSION_time(1,11,0)
import qualified Data.Time.Calendar.Quarter as Time
#endif
```
whereas it should be (and is [in this repo](https://github.com/mgsloan/store/blob/master/test/Data/StoreSpec.hs)):
```
#if MIN_VERSION_time(1,11,0)
import qualified Data.Time.Calendar.Quarter as Time
import qualified Data.Time.Calendar.WeekDate as Time
#endif
```
Also, there is no changelog for 0.7.17, but that's minor.

-- Vekhir

**Comment by mgsloan** [comment]
Thanks @Vekhir !  I think I hadn't noticed that my `git pull` was incomplete when uploading the packages.  Uploaded new ones with incremented versions

**Comment by Vekhir** [comment]
Works now. Thank you!
